version: '3.9'

services:
  currency-naming-server:
    image: armosdocker/spring-microservices-currency-naming-server:0.0.1-SNAPSHOT
    mem_reservation: 100M
    ports:
      - '8761:8761'
    networks:
      - currency-network

  currency-rabbitmq:
    image: rabbitmq
    mem_reservation: 250M
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - currency-network

  currency-zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_reservation: 250M
    ports:
      - "9411:9411"
    networks:
      - currency-network
    environment:
      RABBIT_URI: amqp://guest:guest@currency-rabbitmq:5672
    depends_on:
      - currency-rabbitmq
    restart: always #Restart if there is a problem starting up

  currency-api-gateway:
    image: armosdocker/spring-microservices-currency-api-gateway:0.0.1-SNAPSHOT
    mem_reservation: 150M
    ports:
      - '8765:8765'
    networks:
      - currency-network
    depends_on:
      - currency-naming-server
      - currency-rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://currency-naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://currency-zipkin-server:9411
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: currency-rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  currency-exchange-service:
    image: armosdocker/spring-microservices-currency-exchange-service:0.0.1-SNAPSHOT
    mem_reservation: 250M
    ports:
      - '8000:8000'
    networks:
      - currency-network
    depends_on:
      - currency-naming-server
      - currency-rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://currency-naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://currency-zipkin-server:9411
      RABBIT_URI: amqp://guest:guest@currency-rabbitmq:5672
      SPRING_RABBITMQ_HOST: currency-rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  currency-conversion-service:
    image: armosdocker/spring-microservices-currency-conversion-service:0.0.1-SNAPSHOT
    mem_reservation: 250M
    ports:
      - '8100:8100'
    networks:
      - currency-network
    depends_on:
      - currency-naming-server
      - currency-rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://currency-naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://currency-zipkin-server:9411
      RABBIT_URI: amqp://guest:guest@currency-rabbitmq:5672
      SPRING_RABBITMQ_HOST: currency-rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

networks:
  currency-network:
